/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("io.github.goooler.shadow") version "8.1.8"
    distribution
}

repositories {
    mavenLocal()
    mavenCentral()
}

group = "jp.co.sony.csl.dcoes.apis"
version = "3.9.14"
description = "APIS LOG"

java.sourceCompatibility = JavaVersion.VERSION_11
java.targetCompatibility = JavaVersion.VERSION_11

dependencies {
    api(platform("jp.co.sony.csl.dcoes.apis:apis-bom:${project.version}"))
    api("jp.co.sony.csl.dcoes.apis:apis-common:${project.version}")
    api(libs.io.vertx.vertx.core)
    api(libs.io.vertx.vertx.mongo.client)
    
    testImplementation(libs.io.vertx.vertx.unit)
    testImplementation(libs.junit.junit)
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
    options.compilerArgs.add("-Xlint:deprecation")
    options.isDeprecation = true
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
    (options as StandardJavadocDocletOptions).apply {
        author(true)
        showFromPrivate()
        addStringOption("Xdoclint:none", "-quiet")
    }
}

// Replicate maven-shade-plugin behavior
tasks.shadowJar {
    isZip64 = true
    archiveClassifier.set("fat")
    manifest {
        attributes(
            "Main-Class" to "jp.co.sony.csl.dcoes.apis.common.util.vertx.ApisLauncher",
            "Main-Verticle" to "jp.co.sony.csl.dcoes.apis.tools.log.util.Starter"
        )
    }
    mergeServiceFiles()
}

// Custom task to generate verify.info using the groovy script
val generateVerifyInfo by tasks.registering(Exec::class) {
    commandLine("groovy", "generateVerifyInfo.groovy", project.version, "$buildDir/verify.info")
    outputs.file("$buildDir/verify.info")
}

// Configure distribution to match maven-assembly-plugin
distributions {
    main {
        distributionBaseName.set("apis-log")
        contents {
            // Include the fat jar
            from(tasks.shadowJar) {
                into("/")
            }
            // Include shell scripts from src/main/resources
            from("src/main/resources") {
                include("stop.sh", "kill.sh", "stop-kill.sh", "verify.sh")
                into("/")
            }
            // Include verify.info generated by groovy
            from(generateVerifyInfo) {
                into("/")
            }
        }
    }
}

// Assemble task depends on the distribution
tasks.assemble {
    dependsOn(tasks.distTar, tasks.distZip)
}
